# Generated by Django 6.0.5 on 2026-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='fa-shield-alt', max_length=50, verbose_name='Иконка')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
        ),
    ]
